#!/bin/bash

#BANNER

echo "                               _                           _ _      _                           _       _   "
sleep 1
echo "                              (_)                         | (_)    (_)                         (_)     | |  "
sleep 1
echo "  __ _ _ __  _ __   ___  _   _ _ _ __   __ _   _ __   ___ | |_  ___ _  ___  ___   ___  ___ _ __ _ _ __ | |_ "
sleep 1
echo " / _  | '_ \| '_ \ / _ \| | | | | '_ \ / _  | | '_ \ / _ \| | |/ __| |/ _ \/ __| / __|/ __| '__| | '_ \| __|"
sleep 1
echo "| (_| | | | | | | | (_) | |_| | | | | | (_| | | |_) | (_) | | | (__| |  __/\__ \ \__ \ (__| |  | | |_) | |_ "
sleep 1
echo " \__,_|_| |_|_| |_|\___/ \__, |_|_| |_|\__, | | .__/ \___/|_|_|\___|_|\___||___/ |___/\___|_|  |_| .__/ \__|"
sleep 1
echo "                          __/ |         __/ | | |                                                | |        "
sleep 1
echo "                         |___/         |___/  |_|                                                |_|        "
sleep 4

#SETTING COLORS

BG_BLACK="\033[40m"
BG_RED="\033[41m"
BG_GREEN="\033[42m"
BG_YELLOW="\033[43m"
BG_BLUE="\033[44m"
BG_MAGENTA="\033[45m"
BG_CYAN="\033[46m"
BG_WHITE="\033[47m"

# Bright Background Colors
BG_BBLACK="\033[100m"
BG_BRED="\033[101m"
BG_BGREEN="\033[102m"
BG_BYELLOW="\033[103m"
BG_BBLUE="\033[104m"
BG_BMAGENTA="\033[105m"
BG_BCYAN="\033[106m"
BG_BWHITE="\033[107m"

# Reset
RESET="\033[0m"

# CHANGING PERMISSIONS
echo -e "${BG_RED}Changing permissions...${RESET}"
sudo find /etc/apt/ -type d -exec chmod 755 {} \;
sudo find /etc/apt/ -type f -exec chmod 644 {} \;
sudo chattr -R -ia /etc/apt
sudo chown -R root:root /etc/apt
sudo setfacl -Rb /etc/apt/*
sudo setfacl -Rb /etc/apt/*/*
echo -e "${BG_GREEN}Done!${RESET}\n"

#00aptitude
echo -e "${BG_RED}Editing 00aptitude${RESET}"
sudo echo "Aptitude::Get-Root-Command "sudo:/usr/bin/sudo";" > /etc/apt/apt.conf.d/00aptitude
